<#
.SYNOPSIS
    F.1 Phase 6 — Voice Edit regression runner.

.DESCRIPTION
    Two layers, same shape as tests/history/run-tests.ps1:

    1. AHK-native unit driver (voice-edit-tests.ahk) exercising the REAL
       functions from QuickSay.ahk: GetVoiceEditMetaPrompt(), BuildVoiceEditPrompt(),
       EscapeJson(), ParseConfig(), GetDefaultConfig(). These are extracted
       verbatim (see lib/extract-functions.ps1) into a generated include —
       no copied/rewritten logic to drift from source. lib/JSON.ahk and
       lib/dpapi.ahk are included directly (real, safe: no autoexec GUI).

    2. Source assertions over QuickSay.ahk for structural/wiring properties
       that can't be exercised as isolated unit calls (hotkey labels,
       ordering of statements inside StopAndProcess/HandleVoiceEditResult,
       absence of a stale reference in RegisterVoiceEditHotkey).

    Never touches Development/data/ or config.json. Does not modify any
    production source file.

.EXAMPLE
    pwsh tests\voice-edit\run-tests.ps1
    powershell -File tests\voice-edit\run-tests.ps1

.NOTES
    Built in F.1 Phase 6. Prereq: AutoHotkey v2 at
    'C:\Program Files\AutoHotkey\v2\AutoHotkey64.exe' (falls back to the
    bundled Development\AutoHotkey64.exe). Run via the PowerShell tool, not
    the bash sandbox (the AHK GUI host needs a real window station).
#>
[CmdletBinding()]
param([switch]$KeepArtifacts)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Here   = $PSScriptRoot
$DevDir = (Resolve-Path (Join-Path $Here '..\..')).Path

. (Join-Path $Here 'lib\extract-functions.ps1')

$Ahk = 'C:\Program Files\AutoHotkey\v2\AutoHotkey64.exe'
if (-not (Test-Path $Ahk)) { $Ahk = Join-Path $DevDir 'AutoHotkey64.exe' }
if (-not (Test-Path $Ahk)) {
    Write-Host "AutoHotkey64.exe not found (looked in Program Files and $DevDir)." -ForegroundColor Red
    exit 2
}

$Scratch = Join-Path ([System.IO.Path]::GetTempPath()) ("qs-voiceedit-" + [guid]::NewGuid().ToString('N').Substring(0,8))
New-Item -ItemType Directory -Path $Scratch -Force | Out-Null
# The AHK driver's own results file lives directly in $Scratch (parent holds
# the handle open for the run); nothing here does a DirDelete of a subdir, so
# the known DirDelete-hang gotcha does not apply, but we still keep generated
# driver inputs in a distinct subdir for hygiene/parity with other harnesses.
$workDir = Join-Path $Scratch 'work'
New-Item -ItemType Directory -Path $workDir -Force | Out-Null

$results = @()   # [pscustomobject]{ Name; Status; Detail }
$fatal   = @()

$mainPath = Join-Path $DevDir 'QuickSay.ahk'
if (!(Test-Path $mainPath)) { throw "QuickSay.ahk not found at $mainPath" }

# --- Generate the include: real function bodies extracted from QuickSay.ahk ---
$fnNames = @('GetVoiceEditMetaPrompt', 'GenEditNonce', 'BuildVoiceEditPrompt', 'EscapeJson', 'ParseConfig', 'GetDefaultConfig')
$functions = Get-AhkFunctions -SourcePath $mainPath -Names $fnNames

$generatedDir  = Join-Path $Here '.generated'
$generatedFile = Join-Path $generatedDir 'voice-edit-functions.ahk'
$header = "; AUTO-GENERATED by tests\voice-edit\run-tests.ps1 — do not edit by hand.`n; Extracted verbatim from QuickSay.ahk: " + ($fnNames -join ', ')
Write-AhkFunctionsFile -Functions $functions -OutPath $generatedFile -Header $header | Out-Null

# --- Layer 1: AHK unit driver --------------------------------------------------
$driver  = Join-Path $Here 'voice-edit-tests.ahk'
$resFile = Join-Path $Scratch 'voice-edit.results.txt'
$errFile = Join-Path $Scratch 'voice-edit.stderr.txt'

$p = Start-Process -FilePath $Ahk `
        -ArgumentList @('/ErrorStdOut', $driver, $resFile) `
        -NoNewWindow -PassThru -RedirectStandardError $errFile
if (-not $p.WaitForExit(60000)) {
    $p.Kill(); $p.WaitForExit()
    $fatal += "voice-edit-tests.ahk timed out (60s)."
}

if (Test-Path $resFile) {
    $raw = Get-Content $resFile -Encoding UTF8
    if ($raw -notcontains '__DONE__') {
        $stderr = if (Test-Path $errFile) { (Get-Content $errFile -Raw).Trim() } else { '' }
        $fatal += "voice-edit-tests.ahk did not complete. stderr: $stderr"
    }
    foreach ($line in ($raw | Where-Object { $_ -and $_ -ne '__DONE__' })) {
        $parts = $line -split "`t", 3
        $results += [pscustomobject]@{
            Name   = $parts[0]
            Status = $parts[1]
            Detail = if ($parts.Count -ge 3) { $parts[2] } else { '' }
        }
    }
} else {
    $stderr = if (Test-Path $errFile) { (Get-Content $errFile -Raw).Trim() } else { '' }
    $fatal += "voice-edit-tests.ahk produced no results file. stderr: $stderr"
}

# --- Layer 2: source assertions over QuickSay.ahk (structural/wiring) ---------
function Add-SourceAssertion {
    param([string]$Name, [bool]$Ok, [string]$Detail)
    $script:results += [pscustomobject]@{
        Name = $Name; Status = ($Ok ? 'PASS' : 'FAIL'); Detail = $Detail
    }
}

$mainSrc = Get-Content $mainPath -Raw -Encoding UTF8

# S1 — the dictation key-up hotkey must not stop a Voice Edit recording: the
# RecordingPurpose guard must appear BEFORE the StopAndProcess() call inside
# the `LCtrl & LWin Up` block.
$hotkeyBlockOk = $false
$hotkeyDetail  = "block not found"
if ($mainSrc -match '(?ms)^LCtrl & LWin Up::.*?^\}') {
    $block = $matches[0]
    $idxGuard = $block.IndexOf('RecordingPurpose = "voiceEdit"')
    $idxStop  = $block.IndexOf('StopAndProcess()')
    if ($idxGuard -ge 0 -and $idxStop -ge 0 -and $idxGuard -lt $idxStop) {
        $hotkeyBlockOk = $true
        $hotkeyDetail  = ''
    } else {
        $hotkeyDetail = "guard@$idxGuard stop@$idxStop (expected guard before stop, both found)"
    }
}
Add-SourceAssertion 'S1_dictation_hotkey_guards_voiceedit_before_stop' $hotkeyBlockOk $hotkeyDetail

# S2 — StopAndProcess reads-and-resets RecordingPurpose/VoiceEditSelectedText
# immediately after isProcessing := true, so every exit path leaves state clean.
try {
    $stopBody = Get-AhkFunctionBody -Lines ($mainSrc -split "`r?`n") -Name 'StopAndProcess'
    # Window generous enough to span the explanatory comment block between
    # `isProcessing := true` and the read-and-reset lines, but still tight
    # (not the whole function) — this is a proximity check, not just an
    # ordering check.
    $s2Ok = ($stopBody -match '(?s)isProcessing\s*:=\s*true.{0,400}purpose\s*:=\s*RecordingPurpose.{0,100}RecordingPurpose\s*:=\s*"dictate"')
    Add-SourceAssertion 'S2_stopandprocess_read_reset_after_isprocessing' $s2Ok `
        ($s2Ok ? '' : 'read-and-reset block not found immediately after isProcessing := true')
} catch {
    Add-SourceAssertion 'S2_stopandprocess_read_reset_after_isprocessing' $false "extraction failed: $($_.Exception.Message)"
}

# S3 — HandleVoiceEditResult must never paste on a failure path: PasteReplacement
# appears exactly once, and only after the ResultText empty-check.
try {
    $handleBody = Get-AhkFunctionBody -Lines ($mainSrc -split "`r?`n") -Name 'HandleVoiceEditResult'
    $pasteCount = ([regex]::Matches($handleBody, 'PasteReplacement\(')).Count
    $idxEmptyCheck = $handleBody.IndexOf('if (ResultText = "")')
    $idxPaste      = $handleBody.IndexOf('PasteReplacement(')
    $s3Ok = ($pasteCount -eq 1) -and ($idxEmptyCheck -ge 0) -and ($idxPaste -gt $idxEmptyCheck)
    $s3Detail = if ($s3Ok) { '' } else { "PasteReplacement count=$pasteCount, idxEmptyCheck=$idxEmptyCheck, idxPaste=$idxPaste" }
    Add-SourceAssertion 'S3_handlevoiceeditresult_paste_only_once_after_emptycheck' $s3Ok $s3Detail
} catch {
    Add-SourceAssertion 'S3_handlevoiceeditresult_paste_only_once_after_emptycheck' $false "extraction failed: $($_.Exception.Message)"
}

# S4 — RegisterVoiceEditHotkey must not reference hotkeyMode (Voice Edit is
# hold-to-talk only; sticky/toggle semantics are deliberately unsupported).
try {
    $registerBody = Get-AhkFunctionBody -Lines ($mainSrc -split "`r?`n") -Name 'RegisterVoiceEditHotkey'
    $s4Ok = -not ($registerBody -match 'hotkeyMode')
    Add-SourceAssertion 'S4_registervoiceedithotkey_no_hotkeymode_reference' $s4Ok `
        ($s4Ok ? '' : 'RegisterVoiceEditHotkey unexpectedly references hotkeyMode')
} catch {
    Add-SourceAssertion 'S4_registervoiceedithotkey_no_hotkeymode_reference' $false "extraction failed: $($_.Exception.Message)"
}

# S5 — HandleVoiceEditResult records the edit to history with kind "voiceEdit"
# and the spoken instruction, and only on the success path (after PasteReplacement).
try {
    $handleBody2 = Get-AhkFunctionBody -Lines ($mainSrc -split "`r?`n") -Name 'HandleVoiceEditResult'
    $idxPaste2 = $handleBody2.IndexOf('PasteReplacement(')
    $idxSave   = $handleBody2.IndexOf('SaveToHistory(')
    $hasVoiceEditKind = ($handleBody2 -match 'SaveToHistory\([^\r\n]*"voiceEdit"')
    $s5Ok = ($idxPaste2 -ge 0) -and ($idxSave -gt $idxPaste2) -and $hasVoiceEditKind
    $s5Detail = if ($s5Ok) { '' } else { "idxPaste=$idxPaste2 idxSave=$idxSave voiceEditKind=$hasVoiceEditKind" }
    Add-SourceAssertion 'S5_handlevoiceeditresult_saves_history_with_instruction' $s5Ok $s5Detail
} catch {
    Add-SourceAssertion 'S5_handlevoiceeditresult_saves_history_with_instruction' $false "extraction failed: $($_.Exception.Message)"
}

# --- Report --------------------------------------------------------------------
Write-Host ""
Write-Host "F.1 Voice Edit regression (Phase 6)" -ForegroundColor Cyan
Write-Host ("-" * 70)

$pass = 0; $fail = 0
foreach ($t in $results) {
    if ($t.Status -eq 'PASS') {
        $pass++
        Write-Host ("  PASS  " + $t.Name) -ForegroundColor Green
    } else {
        $fail++
        $msg = "  FAIL  " + $t.Name
        if ($t.Detail) { $msg += "  [" + $t.Detail + "]" }
        Write-Host $msg -ForegroundColor Red
    }
}
foreach ($e in $fatal) { Write-Host ("  ERROR " + $e) -ForegroundColor Red }

Write-Host ("-" * 70)
Write-Host ("  {0} passed, {1} failed, {2} total" -f $pass, $fail, ($pass + $fail))

if (-not $KeepArtifacts) {
    Remove-Item $Scratch -Recurse -Force -ErrorAction SilentlyContinue
} else {
    Write-Host "  artifacts: $Scratch" -ForegroundColor DarkGray
    Write-Host "  generated: $generatedFile" -ForegroundColor DarkGray
}

if ($fail -gt 0 -or $fatal.Count -gt 0) { exit 1 } else { exit 0 }
